# Generated by Django 5.1.1 on 2024-10-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lastname',
            field=models.CharField(default='', max_length=122),
        ),
    ]
