# Generated by Django 5.1.1 on 2024-10-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_contact_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='lastname',
        ),
        migrations.AddField(
            model_name='contact',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
