# Generated by Django 5.1.1 on 2024-10-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='description',
        ),
    ]
