# Generated by Django 5.1.1 on 2024-10-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_cartitem_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
