# Generated by Django 5.1.1 on 2024-10-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='description',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
