# Generated by Django 5.1.1 on 2024-10-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='fixed_id',
            field=models.CharField(default="nice", max_length=100, unique=False),
            preserve_default=False,
        ),
    ]
