# Generated by Django 5.1.1 on 2024-10-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_cartitem_fixed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='fixed_id',
            field=models.DecimalField(default=100,decimal_places=2, max_digits=10),
        ),
    ]
