# Generated by Django 5.1.1 on 2024-10-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_cartitem_fixed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='fixed_id',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
