# Generated by Django 5.1.1 on 2024-10-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_cartitem_fixed_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='fixed_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='fixed_id',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
