# Generated by Django 5.1.1 on 2024-10-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_cartitem_fixed_id_cart_fixed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='fixed_id',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
